### ISSUE TITLE
Trying to run directly Emoji encoded file fails

### ISSUE THREAD

**Issue by suda** [suda/python-emoji-encoding#1]
See https://github.com/suda/python-emoji-encoding#known-issues

**Comment by belonesox** [comment]
Workaround dont work for me on Windows/Anaconda 

```
C:\projects\test-emoji>C:\Anaconda3\python.exe bootstrap.py
Traceback (most recent call last):
File "bootstrap.py", line 1, in <module>
import emoj
File "C:\projects\test-emoji\emoj.py", line 0
SyntaxError: unknown encoding: emoji
C:\projects\test-emoji>C:\Anaconda3\python.exe -V
Python 3.6.8 :: Anaconda custom (64-bit)
```

What is wrong?

**Comment by suda** [comment]
Hmm, that is interesting. Unfortunately, I don't have a Windows machine to test it. Would you be able to do some experiments and figure out what's wrong?
